image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- go
- hut
- ruby-full
- ruby-dev
environment:
site: 1mb.club
sources:
- https://git.sr.ht/~bt/1mb-club
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd 1mb-club
    sudo bundle install
    sudo bundle exec jekyll build
- package: |
    cd 1mb-club/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d 1mb.club site.tar.gz