title: 1MB Club
description: An exclusive membership for web pages weighing less than 1 megabyte.
baseurl: '' # the subpath of your site, e.g. /blog
url: https://1mb.club # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Bradley Taunt
  email: hello@tdarb.org

# Collections
collections:
  site_listings:
    output: false

permalink: /blog/:title/

exclude:
  - generate.sh
  - README.md

include:
  - netlify.toml
  - .htaccess
